controllers/PageController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\readModels\PagesReadRepository;
use app\readModels\SiteReadRepository;
use yii\web\NotFoundHttpException;
/**
 * Page controller
 */

class PageController extends Controller
{
    /**
     * @inheritdoc
     */
    private $page;
    private $site;

    public function __construct($id, $module, PagesReadRepository $page,  SiteReadRepository $site, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->site = $site;
        $this->page = $page;
    }


    public function actionPage($slug)
    {
        return $this->render('page', [
            'page' => $this->findModel($slug),
            'menu' => $this->site->findPageMenuAll() 
        ]);
    }
	
	protected function findModel ($slug) {
	     if (($page = $this->page->findOne($slug)) != null ) {
		    return $page; }
			else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
	
	}
	
	public function actionDistionary($slug, $id)
    {
	    if (!$ds = $this->findModel($slug)->getDictionary()->where(['id'=>$id])->one()) {
		  throw new NotFoundHttpException('The requested distionary does not exist.');
		}
        return $this->renderAjax('distionary', [
            'ds' => $ds,
        ]);
    }

    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\readModels\SiteReadRepository;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    private $page;

    public function __construct($id, $module, SiteReadRepository $page, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->page = $page;
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index',['pages' => $this->page]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(["/admin/pages"]);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
use rmrevin\yii\fontawesome\FA;

/* @var $this yii\web\View */

$this->title = 'Главная';
?>
<div class="site-index">
   <div class="row" style="background-color: #FFF">
    <div class="col-md-9  jb">
        <h1>Добро пожаловать <br /> в "Виртуальный музей" </h1>

        <p class="lead">

Посещая экспозиции музея, 
Вы совершите экскурс в историю не только Гродненской специальной школы-интерната 
для детей с нарушением слуха,
но и в историю и культуру неслышащих всего мира, 
познакомитесь с историей сурдопедагогики.</p>

</div>

 <div class="col-md-3 update-data">
                <h2>Последние обновления</h2>

                   <?php foreach ($pages->findPagesDateUpdate() as $page_u) { ?>
                   <h4><?= $page_u->title ?></h4>
                   <p><?=  Yii::$app->formatter->asDate($page_u->updated_at, 'long'); ?> </p>
                  
                  <?= Html::a('Смотреть',['page/page', 'slug'=>$page_u->slug],
                  ['class'=> 'btn btn-default'])?>
              <?php }?>
            </div>
</div>

    <div class="body-content">

             <?php foreach ($pages->findPagesLimit() as $key => $page) { ?>
             <div class="row" style=" background-color: <?= $key%2 == 0 ? "#E9DB89" : "#FFF"?>">
            <div class="col-md-12" style="margin: 25px 0" >
                <center>
                <h2><?= FA::icon($page->icon) ?>  <?= $page->title ?></h2>

                <?php if($page->getChildren()) { ?>
<div class="row">
       <?php foreach ($page->getChildren()->all()  as $key1 => $children) {?>
            <article>

                 <div class="col-md-4">
                <h4> <?= Html::a($children->title,['page/page', 'slug'=>$children->slug])?></h4>
                 <div class="border"></div>
                 <p><?= $children->description ?></p>
              </div>
              <?php if ( $key1%3== 2){?>
                  <div class="clearfix"></div>
              <?php } ?>
            </article>
        <?php } ?>
        </div>
        <?php } ?>
        </center>
            </div>
            </div>
             <?php } ?>
           
        

    </div>
</div>

<?php  


       // var_dump($arr);

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для входа:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Вход', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
       Вы можете войти в систему с <strong>admin/admin</strong>.
    </div>
</div>